CREATE SCHEMA IC;

/* ITENS COLETIVOS */
CREATE TABLE IC.IC001 (
     IC001_NR_ITEM       BIGSERIAL     PRIMARY KEY,
     IC001_NR_MORADIA    INTEGER       NOT NULL,
     IC001_NR_MORADOR    INTEGER       NOT NULL,
     IC001_VC_ITEM       VARCHAR(40)   NOT NULL,
     IC001_IT_SITUAC     NUMERIC(2,0)  NOT NULL,
     IC001_DT_ULTATU     TIMESTAMP     NOT NULL,
     IC001_DT_INCLUS     TIMESTAMP     NOT NULL
);

/* COMPRAS */
CREATE TABLE IC.IC002 (
    IC002_NR_COMPRA      BIGSERIAL     PRIMARY KEY,
    IC002_NR_ITEM        INTEGER       NOT NULL       UNIQUE,
    IC002_NR_MORADOR     INTEGER       NOT NULL,
    IC002_NR_QTDE        NUMERIC(5,0)  NOT NULL,
    IC002_VL_VALOR       NUMERIC(10,2) NOT NULL,
    IC002_IT_SITUAC      NUMERIC(2,0)  NOT NULL,
    IC002_DT_ULTATU      TIMESTAMP     NOT NULL,
    IC002_DT_INCLUS      TIMESTAMP     NOT NULL
);

ALTER TABLE IC.IC001 ADD FOREIGN KEY (IC001_NR_MORADIA) REFERENCES AD.AD003(AD003_NR_MORADIA);
ALTER TABLE IC.IC001 ADD FOREIGN KEY (IC001_NR_MORADOR) REFERENCES AD.AD001(AD001_NR_MORADOR);
ALTER TABLE IC.IC002 ADD FOREIGN KEY (IC002_NR_ITEM)    REFERENCES IC.IC001(IC001_NR_ITEM);
ALTER TABLE IC.IC002 ADD FOREIGN KEY (IC002_NR_MORADOR) REFERENCES AD.AD001(AD001_NR_MORADOR);