CREATE SCHEMA CC;

/* CONTAS MENSAIS */
CREATE TABLE CC.CC001 (
    CC001_NR_CONTAM     BIGSERIAL     PRIMARY KEY,
    CC001_NR_TPCONTA    INTEGER       NOT NULL,
    CC001_NR_MORADIA    INTEGER       NOT NULL,
    CC001_DT_DDVENC     NUMERIC(2,0)  NOT NULL,
    CC001_DT_AMVENC     NUMERIC(6,0)  NOT NULL,
    CC001_VL_VALOR      NUMERIC(10,2) NOT NULL,
    CC001_IT_SITUAC     NUMERIC(2,0)  NOT NULL,
    CC001_DT_ULTATU     TIMESTAMP     NOT NULL,
    CC001_DT_INCLUS     TIMESTAMP     NOT NULL
);

/* TIPO CONTAS */
CREATE TABLE CC.CC002 (
    CC002_NR_TPCONTA   BIGSERIAL     PRIMARY KEY,
    CC002_VC_TPCONTA   VARCHAR(20)   NOT NULL,
    CC002_NR_MORADIA   INTEGER       NOT NULL,
    CC002_IT_RECOR     NUMERIC(2,0)  NOT NULL,
    CC002_IT_SITUAC    NUMERIC(2,0)  NOT NULL,
    CC002_DT_ULTATU    TIMESTAMP     NOT NULL,
    CC002_DT_INCLUS    TIMESTAMP     NOT NULL
);

/* ORÇAMENTO */
CREATE TABLE CC.CC003 (
    CC003_NR_ORCAM     BIGSERIAL     PRIMARY KEY,
    CC003_NR_CONTAM    INTEGER       NOT NULL,
    CC003_NR_MORADIA   INTEGER       NOT NULL,
    CC003_NR_MORADOR   INTEGER       NOT NULL,
    CC003_VL_VALORM    NUMERIC(10,2) NOT NULL,
    CC003_DT_PAGAM     NUMERIC(8,0)      NULL,
    CC003_IT_SITUAC    NUMERIC(2,0)  NOT NULL,
    CC003_IT_OKADM     NUMERIC(2,0)  NOT NULL,
    CC003_DT_ULTATU    TIMESTAMP     NOT NULL,
    CC003_DT_INCLUS    TIMESTAMP     NOT NULL
);

ALTER TABLE CC.CC001 ADD FOREIGN KEY (CC001_NR_TPCONTA) REFERENCES CC.CC002(CC002_NR_TPCONTA);
ALTER TABLE CC.CC001 ADD FOREIGN KEY (CC001_NR_MORADIA) REFERENCES AD.AD003(AD003_NR_MORADIA);
ALTER TABLE CC.CC002 ADD FOREIGN KEY (CC002_NR_MORADIA) REFERENCES AD.AD003(AD003_NR_MORADIA);
ALTER TABLE CC.CC003 ADD FOREIGN KEY (CC003_NR_MORADIA) REFERENCES AD.AD003(AD003_NR_MORADIA);
ALTER TABLE CC.CC003 ADD FOREIGN KEY (CC003_NR_MORADOR) REFERENCES AD.AD001(AD001_NR_MORADOR);
ALTER TABLE CC.CC003 ADD FOREIGN KEY (CC003_NR_CONTAM)  REFERENCES CC.CC001(CC001_NR_CONTAM);