CREATE SCHEMA AD;

/* MORADOR */
CREATE TABLE AD.AD001 (
    AD001_NR_MORADOR   BIGSERIAL    PRIMARY KEY,
    AD001_VC_NOME      VARCHAR(30)  NOT NULL,
    AD001_VC_SOBREN    VARCHAR(50)  NOT NULL,
    AD001_NR_CPF       VARCHAR(11)  NOT NULL    UNIQUE,
    AD001_VC_EMAIL     VARCHAR(150) NOT NULL    UNIQUE,
    AD001_VC_LOGIN     VARCHAR(30)  NOT NULL    UNIQUE,
    AD001_VC_PASSW     VARCHAR      NOT NULL,
    AD001_DT_ENTRADA   NUMERIC(8,0) NOT NULL,
    AD001_NR_TPMOR     INTEGER      NOT NULL,
    AD001_IT_SITUAC    NUMERIC(2,0) NOT NULL,
    AD001_DT_ULTATU    TIMESTAMP    NOT NULL,
    AD001_DT_INCLUS    TIMESTAMP    NOT NULL
);

/* TIPO MORADOR */
CREATE TABLE AD.AD002 (
    AD002_NR_TPMOR     BIGSERIAL    PRIMARY KEY,
    AD002_VC_TPMOR     VARCHAR(20)  NOT NULL,
    AD002_IT_SITUAC    NUMERIC(2,0) NOT NULL,
    AD002_DT_ULTATU    TIMESTAMP    NOT NULL,
    AD002_DT_INCLUS    TIMESTAMP    NOT NULL
);

/* MORADIAS */
CREATE TABLE AD.AD003 (
    AD003_NR_MORADIA    BIGSERIAL    PRIMARY KEY,
    AD003_VC_MORADIA    VARCHAR(15)  NOT NULL,
    AD003_NR_ADMMOR     INTEGER      NOT NULL,
    AD003_DT_DDVENC     NUMERIC(2,0)         ,
    AD003_VC_TOKEN      VARCHAR(6)   NOT NULL    UNIQUE,
    AD003_IT_SITUAC     NUMERIC(2,0) NOT NULL,
    AD003_DT_ULTATU     TIMESTAMP    NOT NULL,
    AD003_DT_INCLUS     TIMESTAMP    NOT NULL
);

/* MORADOR X MORADIA */
CREATE TABLE AD.AD004 (
    AD004_NR_MORAD     BIGSERIAL    PRIMARY KEY,
    AD004_NR_MORADIA   INTEGER      NOT NULL,
    AD004_NR_MORADOR   INTEGER      NOT NULL,
    AD004_IT_SITUAC    NUMERIC(2,0) NOT NULL,
    AD004_DT_ULTATU    TIMESTAMP    NOT NULL,
    AD004_DT_INCLUS    TIMESTAMP    NOT NULL
);

ALTER TABLE AD.AD001 ADD FOREIGN KEY (AD001_NR_TPMOR) REFERENCES AD.AD002(AD002_NR_TPMOR);
ALTER TABLE AD.AD003 ADD FOREIGN KEY (AD003_NR_ADMMOR) REFERENCES AD.AD001(AD001_NR_MORADOR);
ALTER TABLE AD.AD004 ADD FOREIGN KEY (AD004_NR_MORADIA) REFERENCES AD.AD003(AD003_NR_MORADIA);
ALTER TABLE AD.AD004 ADD FOREIGN KEY (AD004_NR_MORADOR) REFERENCES AD.AD001(AD001_NR_MORADOR);
